"""
Product catalog loader.

The catalog file (``product_catalog.json``) is generated by running::

    python apk_analysis/fetch_catalog.py

It maps the BLE advertisement key ``<SERVICE_UUID>_<DEVICE_NAME>`` to per-device
Modbus parameters (address, register count, protocol version).

All functions degrade gracefully when the catalog file is absent — callers
receive ``None`` and fall back to the defaults in ``constants.py``.
"""

from __future__ import annotations

import json
import pathlib
from typing import TypedDict

_CATALOG_PATH = pathlib.Path(__file__).parent / "product_catalog.json"

# Cached catalog so the file is only read once per process.
_cache: dict | None = None


def _load() -> dict:
    global _cache
    if _cache is None:
        if _CATALOG_PATH.exists():
            _cache = json.loads(_CATALOG_PATH.read_text())
        else:
            _cache = {}
    return _cache


def invalidate_cache() -> None:
    """Force the next call to re-read the catalog file from disk."""
    global _cache
    _cache = None


class DeviceParams(TypedDict):
    modbus_address: int
    modbus_count: int
    protocol_version: int


def get_device_params(product_key: str) -> DeviceParams | None:
    """
    Return Modbus parameters for a device identified by its *product key*.

    The product key is ``"<SERVICE_UUID>_<DEVICE_NAME>"`` — the same format
    used by the BrightEMS app's ``productMap``.

    Returns ``None`` when the catalog is unavailable or the key is not found.
    """
    catalog = _load()
    product = catalog.get("products", {}).get(product_key)
    if product is None:
        return None

    # modbus_address / modbus_count may be stored directly on the product
    # (added by the updated fetch_catalog.py) or resolved via the category.
    if "modbus_address" in product and "modbus_count" in product:
        return DeviceParams(
            modbus_address=product["modbus_address"],
            modbus_count=product["modbus_count"],
            protocol_version=product.get("protocol_version", 1),
        )

    # Fallback: resolve through category entry.
    category_id = product.get("category_id", "")
    category = catalog.get("categories", {}).get(category_id, {})
    return DeviceParams(
        modbus_address=category.get("modbus_address", 18),
        modbus_count=category.get("modbus_count", 85),
        protocol_version=product.get("protocol_version", 1),
    )


def list_product_keys() -> list[str]:
    """Return all known product keys from the catalog."""
    return list(_load().get("products", {}).keys())
